const quizData = [
    {
        id:1,
        querstion:"What does HTML stand for?",
        a: "Hyper Text Preprocessor",
        b: "Hyper Text Markup Language",
        c: "Hyper Text Multiple Language",
        d: "Hyper Tool Multi Language",
        correct: "b",
    },
    {
        id:2,
        querstion:"What does CSS stand for?",
        a: "Common Style Sheet",
        b: "Colorful Style Sheet",
        c: "Computer Style Sheet",
        d: "Cascading Style Sheet",
        correct: "d",
    },
    {
        id:3,
        querstion:"What does URL stand for?",
        a: "Uniform Resource Locator",
        b: "Uniform Resource Link",
        c: "Uniform Registered Link",
        d: "Unified Resource Link",
        correct: "a",
    },
    {
        id:4,
        querstion:"What does HTTP stand for?",
        a: "Hyper Text Protocol",
        b: "Hypertext Transfer Protocol",
        c: "Hypertext Transmission Protocol",
        d: "Hyper Text Processes",
        correct: "b",
    },
    {
        id:5,
        querstion:"What does HTTPS stand for?",
        a: "Hypertext Transfer Print",
        b: "Hypertext Transmission Protocol ",
        c: "Hypertext Transmission Protocol",
        d: "Hypertext Transfer Protocol Secure",
        correct: "d",
    },

]